### ISSUE TITLE
`dmd-2.098.0-beta.2` doesn't work (wrong URL)

### ISSUE THREAD

**Issue by kinke** [dlang-community/setup-dlang#50]
From https://github.com/atilaneves/mirror/pull/28/checks?check_run_id=3742108306:
```
Enabling dmd-2.098.0-beta.2
Downloading http://downloads.dlang.org/releases/2.x/2.098.0-beta.2/dmd.2.098.0-beta.2.linux.tar.xz
HTTPError: Unexpected HTTP response: 403
    at /home/runner/work/_actions/dlang-community/setup-dlang/v1.0.5/node_modules/@actions/tool-cache/lib/tool-cache.js:100:25
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/_actions/dlang-community/setup-dlang/v1.0.5/node_modules/@actions/tool-cache/lib/tool-cache.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  httpStatusCode: 403
}
```

**Comment by kinke** [comment]
Correct URL: http://downloads.dlang.org/pre-releases/2.x/2.098.0/dmd.2.098.0-beta.2.linux.tar.xz

**Comment by mihails-strasuns** [comment]
Currently only generic `dmd-beta` version is recognized (which resolves to the latest beta), anything matching `/^(2\.(\d+)\.\d+)(-.+)?$/` is treated as an actual release. This is a bug, will need to enhance beta detection a bit to also recognize `-beta.N` suffix.
