### ISSUE TITLE
'spawn gpg ENOENT' error when building with DMD (self-hosted runner, win 10 x64)

### ISSUE THREAD

**Issue by ttldtor** [dlang-community/setup-dlang#56]
An `spawn gpg ENOENT` error occurred while trying to build a project on a self-hosted runner with DMD ([dmd-latest](https://github.com/ttldtor/diff/blob/9112652e392b4a8c78844e54dcf17ccca29126cd/.github/workflows/d_tests.yml#L11)).
What could be the problem?

**OS:** Windows 10 x64, 21H2 19044.1706
**CPU:** AMD Ryzen 7 3700X
**RAM:** 32GB DDR4
**Error:** 
```
Error: spawn gpg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:470:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn gpg',
  path: 'gpg',
  spawnargs: [
    '--lock-never',
    '--verify',
    '--keyring',
    '/C/actions-runner\\_work\\_temp\\90014403-aad1-4779-8aa5-a2a1a6097825',
    '--no-default-keyring',
    '/C/actions-runner\\_work\\_temp\\6f60e58c-4002-44d8-b84b-c5d3fb578cf9',
    'C:\\actions-runner\\_work\\_temp\\43bfca81-d894-4484-a3c1-5dc93d16880c'
  ]
}
```
**Project:** https://github.com/ttldtor/diff
**Logs:** [logs_9.zip](https://github.com/dlang-community/setup-dlang/files/8702346/logs_9.zip)

The path to gpg **is in PATH**. I can run it from terminal.
All other builds (and ldc on self-hosted [logs_ldc.zip](https://github.com/dlang-community/setup-dlang/files/8702373/logs_ldc.zip)) were successful.
The user responsible for runner has enough rights to write to or read from the directory.

Please, help.

**Comment by ttldtor** [comment]
Perhaps the problem is in the generated paths for gpg tool...

**Comment by ttldtor** [comment]
I looked at the action source codes and saw that there is a path conversion for **msys**. Nowhere did I see this in the requirements for action. I am using **gpg4win**.

**Comment by WebFreak001** [comment]
hm this action is using gpg assuming it is just installed.

Looks like in the [preinstalled software list](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md) GPG is not included, so it's probably being used from msys here.

Don't think there is any better solution than installing it from msys for self hosted runners.

**Comment by ttldtor** [comment]
The fact is that I run runner as a service, so I will need to "do squats and push-ups" so that commands from under it are executed in msys. I have ideas how to do this without fixing the action. Perhaps I can fix this in the workflow. In the worst case, you just have to run runner from under msys.
